#!/usr/bin/env zsh
#
#


# === {{CMD}}  some/dir/
# === {{CMD}}  some/dir/file.txt
# === {{CMD}}  --choose [last|file|dir|...]
create () {
  local +x CMD="$1"; shift

  case "$CMD" in

    --choose)
      local +x FS="$(my_fs choose $@ || :)"
      if [[ -z "$FS" ]]; then
        return 0
      fi

      create "$FS"
      ;;

    */)
      local +x DIR="$CMD"
      local +x REAL="$(realpath -m "$DIR")"

      if [[ -e "$REAL" ]]; then
        echo "!!! Already exists: $DIR" >&2
        exit 2
      fi

      mkdir -p "$DIR"
      echo "=== Created: $DIR" >&2
      ;;

    *) # === Create file:
      local +x FS="$CMD"
      local +x REAL="$(realpath -m "$FS")"
      if [[ -e "$REAL" ]]; then
        echo "!!! Already exists: $FS" >&2
        exit 2
      fi

      if [[ "$FS" == */ ]]; then
        create "$FS"
      else
        mkdir -p "$(dirname "$REAL")"
        touch "$REAL"
        my_fs edit "$FS"
      fi
      ;;

  esac # === $COMMAND $@

} # === end function
