#!/usr/bin/env zsh
#
#

# === {{CMD}}
# === {{CMD}}  DIR  [DIR]  [DIR]
# === List directories, ignoring ./ , .git, lost+found, .Trash, .Trash-1000 , and maxdepth of 1, mindepth of 1
# === Source: find . -maxdepth 1 -mindepth 1 -type d -not -name ".git" -print

_ls_dirs () {
  find -L "$@" -maxdepth 1 -mindepth 1 -type d \
    -not -name ".git"                    \
    -and -not -name "lost+found"         \
    -and -not -name ".Trash"             \
    -and -not -name ".Trash-1000"        \
    -print
}


if [[ -z "$@" ]]; then
  _ls_dirs "./"
  return 0
fi

while [[ ! -z "$@" ]]; do
  _ls_dirs "$1"
  shift
done

