#!/usr/bin/env zsh
#
#

# === {{CMD}}  file
# === Finds device, formats it, and writes file to it.

# From: https://www.digitalocean.com/community/tutorials/how-to-partition-and-format-storage-devices-in-linux

  # sudo fdisk -l
  local +x ISO="$1"; shift
  if [[ ! -e "$ISO" ]]; then
    echo "!!! Not a file: $ISO"
  fi

  local +x IFS=$'\n'
  local +x SIZE_NAME="$(for LINE in $(lsblk -l | tr -s ' '); do
    local +x MOUNT_POINT="$(echo "$LINE" | cut -d' ' -f6)"
    local +x NAME="$(echo "$LINE" | cut -d' ' -f1)"
    local +x SIZE="$(echo "$LINE" | cut -d' ' -f4)"
    if [[ "$MOUNT_POINT" == "disk" ]]; then
      echo "$SIZE" "$NAME"
    fi
  done | sort -h | head -n 1)"
  if [[ -z "$SIZE_NAME" ]]; then
    echo "!!! No drive found." >&2
    exit 1
  fi

  mount_points () {
    lsblk  -l | grep -P '^'$1'\d+.+part\s+.+' | tr -s ' ' | cut -d' ' -f7- || :
  }
  local +x SIZE="$(echo "$SIZE_NAME" | cut -d' ' -f1)"
  local +x NAME="$(echo "$SIZE_NAME" | cut -d' ' -f2)"
  local +x MOUNT_POINT="$(mount_points "$NAME")"
  echo "Found:"
  echo "  MOUNT POINT:  $MOUNT_POINT"
  echo "  SIZE:  $SIZE"
  echo "  NAME:  $NAME"
  echo "  Label: $(ls -l /dev/disk/by-label | grep "$NAME" | cut -d' ' -f10- | tr '\n' ' ')"

  if [[ ! -z "$MOUNT_POINT" ]]; then
    local +x IFS=$'\n'
    for LINE in $(mount_points "$NAME"); do
    echo -n "Is this the corrent partition?: $LINE (y/N): "
    read ans
    case "$ans" in
      y|Y|YES|yes)
        umount "$LINE"
        ;;
      *)
        exit 2
        ;;
    esac
    done
  fi

  echo -n "Is this corrent? (y/N): "
  read ans

  case "$ans" in
    y|Y|YES|yes)
      echo -n "Please wait."; sleep 1
      echo -n '.'; sleep 1; echo -n '.'; sleep 1
      echo -n '.'; sleep 1; echo -n '.'; sleep 1
      echo '.'; sleep 1
      set "-x"
      sudo parted /dev/$NAME mklabel gpt
      sudo parted -a opt /dev/$NAME mkpart primary fat32 0% 100%
      set +x
      echo "=== Results:"
      lsblk | grep "$NAME"

      echo "=== Creating filesystem on partition ${NAME}1 on disk $NAME:"
      # sudo mkfs.ext4 -L USBBOOT /dev/${NAME}1
      # NOTE: Use lower case labels to be compatible with different systems.
      sudo mkfs.vfat -n USBBOOT /dev/${NAME}1
      echo "=== Results of creating filesystem on partition:"
      lsblk --fs | grep "$NAME"

      echo "=== Writing file to disk: $ISO"
      sudo dd bs=4M if="$ISO" of=/dev/$NAME status=progress && sync
      echo "=== Results of writing file to disk:"
      sudo fdisk -l /dev/$NAME
      ;;
    *)
      echo "Exiting..."
      exit 1
      ;;
  esac

