#!/usr/bin/env zsh
#
#



# === {{CMD}}  some/dir/
# === {{CMD}}  some/dir/file.txt
# === {{CMD}}  --choose [last|file|dir|..]

open () {
  case "$@" in

    "--choose "*)
      shift
      local +x FS="$(my_fs choose $@ || :)"
      if [[ -z "$FS" ]]; then
        return 0
      fi

      open "$FS"
      ;;

    */)
      local +x DIR="$1"
      if [[ ! -d "$(realpath -m "$DIR")" ]]; then
        echo "!!! Is not a directory: $DIR" >&2
        exit 2
      fi

      my_fs edit "$DIR"/
      ;;


    *) # === Open file:
      local +x FS="$1"; shift
      local +x REAL="$(realpath -m "$FS")"
      if [[ ! -e "$REAL" ]]; then
        echo "!!! Does not exist: $FS" >&2
        exit 2
      fi

      edit "$FS"
      ;;

  esac # === $COMMAND $@

} # === end function
