#!/usr/bin/env zsh
#
#

# === {{CMD}}  new       new/dir/file.txt
# === {{CMD}}  new       new/dir/
new () {
  local +x FS="$1"; shift

  case "$FS" in
    */)
      mkdir -p "$FS"
      my_fs history insert "$FS"
      ;;

    *)
      local +x DIR="$(dirname "$FS")"
      mkdir -p "$DIR"
      touch "$FS"
      my_fs edit "$FS"
      ;;
  esac
} # === end function
